# Generated by Django 4.2.16 on 2024-09-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram User', 'verbose_name_plural': 'Telegram Users'},
        ),
        migrations.AlterModelTable(
            name='telegramuser',
            table='telegram_users',
        ),
    ]
